export const prOductDeatils = [
  {
    id: 1,
    title: "Nike Air Max Pulse",
    description: "Womens Shoes",
    image: "/BestOfAirMax/IMG01.png",
    price: "₹ 13 995",
  },
  {
    id: 2,
    title: "Nike Air Max",
    description: "Mens's Shoes",
    image: "/BestOfAirMax/IMG02.png",
    price: "₹ 13 995",
  },
  {
    id: 3,
    title: "Nike Air Max 97 SE",
    description: "Mens's Shoes",
    image: "/BestOfAirMax/IMG03.png",
    price: "₹ 16995",
  },

  {
    id: 4,
    title: "Nike Dri-FIT ADV ",
    description: "Men's Short-Sleeve",
    image: "/GearUP/IMG01.PNG",
    price: "₹ 3 895",
  },

  {
    id: 5,
    title: "Nike Dri-FIT Challenger",
    description: "Men's 18cm (approx.) 2-in-1 Versatile Shorts",
    image: "/GearUp/IMG02.png",
    price: "₹ 2 495",
  },

  {
    id: 6,
    title: "Nike Dri-FIT ADV Division",
    description: "Women's Long-Sleeve Running Top",
    image: "/GearUp/IMG03.png",
    price: "₹ 5 295",
  },

  {
    id: 7,
    title: "Nike Fast",
    description: "Women's Mid-Rise 7/8 Running Leggings with Pockets ",
    image: "/GearUP/IMG04.png",
    price: "₹ 3 795",
  },

  {
    id: 8,
    check: "Just In",
    title: "Nike Air Force 1 Mid '07",
    description: "Men's Shoes",
    image: "/products/product01.png",
    color: "1 Colors",
    price: "MRP : ₹ 10 795.00",
  },
  {
    id: 9,
    check: "Just In",
    title: "Nike Court Vision Low Next Nature",
    description: "Men's Shoes",
    image: "/products/product02.png",
    color: "1 Colors",
    price: "MRP : ₹ 4 995.00",
  },
  {
    id: 10,
    check: "Just In",
    title: "Nike Air Force 1 PLT.AF.ORM",
    description: "Women's Shoes",
    image: "/products/product03.png",
    color: "1 Colors",
    price: "MRP : ₹ 8 695.00",
  },
  {
    id: 11,
    check: "Just In",
    title: "Nike Air Force 1 React",
    description: "Men's Shoes",
    image: "/products/product04.png",
    color: "1 Colors",
    price: "MRP : ₹ 13 295.00",
  },
  {
    id: 12,
    check: "Promo Exclusion",
    title: "Air Jordan 1 Elevate Low",
    description: "Women's Shoes",
    image: "/products/product05.png",
    color: "1 Colors",
    price: "MRP : ₹ 11 895.00",
  },
  {
    id: 13,
    check: "Just In",
    title: "Nike Standard Issue",
    description: "Women's Basketball Jersey",
    image: "/products/product06.png",
    color: "1 Colors",
    price: "MRP : ₹ 2 895.00",
  },
  {
    id: 14,
    check: "Promo Exclusion",
    title: "Nike Dunk Low Retro SE",
    description: "Men's Shoes",
    image: "/products/product07.png",
    color: "1 Colors",
    price: "MRP : ₹ 9 695.000",
  },
  {
    id: 15,
    check: "Sustainable Materials",
    title: "Nike Dri-FIT UV Hyverse",
    description: "Men's Short-Sleeve Graphic Fitness Top",
    image: "/products/product08.png",
    color: "1 Colors",
    price: "MRP : ₹ 2 495.00",
  },
  {
    id: 16,
    check: "Just In",
    title: "Nike Court Vision Low",
    description: "Men's Shoes",
    image: "/products/product09.png",
    color: "1 Colors",
    price: "MRP : ₹ 5 695.00",
  },
];
